core/admin.py

It is the same amount of code, but groups things more nicely.

Use admin.register decorator.

---

core/admin.py

Just a little feature that's been sitting in my git stash for a few days that shows a preview of the log on the admin panel

Add log preview to Admin panel

---

core/admin.py
core/models.py
core/tasks.py
core/urls.py
core/validators.py
core/views.py
manage.py
socom/settings/development.py
socom/urls.py
tox.ini

Run `tox -e lint`.
This adds a tox file with linting settings.  Although there is some start for running pytest, that isn't complete.

Add linting for python.

---

core/admin.py

Github history clean version of log preview.

Log preview

---

core/templates/base.html

Template tags inside HTML comments will still try to be rendered, and may cause failures.

Use Django comments to disable HTML

---

setup.py

See https://github.com/celery/celery/issues/6145.

celery 4.4.4 is broken.  Avoid it.

---

core/templates/admin/add_flower.html
core/urls.py
docker-compose.override.yml
docker-compose.yml
setup.py

This still needs to be added to the Heroku deployment.
Resolves #53.

Add flower container and routing.

---

core/admin.py
core/urls.py
geodata/admin.py
geodata/models/__init__.py
geodata/urls.py
geodata/views.py
rgd/utility.py

This also exposes selected top-level geodata models in a more uniform way.

Allow downloading geodata from local systems.

---

core/templates/base.html
core/templates/index.html
geodata/templates/geodata/raster_entries.html
geodata/urls.py
geodata/views.py

Fix some typos.  Remove some debug code.

Add rasters to the home page links.

---

geodata/search.py
geodata/serializers.py
geodata/urls.py

This also changes the near_point results to return geojson rather than WKT.

Add endpoints to get the extents of geospatial data.

---

geodata/models/imagery/base.py
geodata/templates/geodata/raster_entries.html

There might be a better way to do this, but it avoids storing redundant data in the database.

Add some aggregation properties to raster entries.

---

geodata/models/imagery/base.py

This also shows ImageEntry names as part of their __str__ to make it easier to select them when making an ImageSet or RasterEntry.

Autopopulate ImageSet names.

---

.circleci/config.yml
tox.ini

Add coverage reporting to codecov.io and generate HTML coverage reports locally

Coverage Reporting

---

codecov.yml

This adds some basic thresholds for coverage on branches.

Add a config file for codecov.

---

rgd/settings.py
rgd/utility.py
setup.py

Don't import gis functions in utility module; it can get imported before the settings have found GDAL.

Handle changes to s3-file-field.

---

core/migrations/0001_initial.py
core/migrations/0002_dataset_tasks.py
core/migrations/0006_auto_20200424_1239.py
core/migrations/0008_auto_20200427_2022.py
core/migrations/0009_auto_20200427_2027.py
geodata/migrations/0002_django31_jsonfield_import.py
geodata/tests/test_geometry.py
geodata/tests/test_imagery.py

The latest of black breaks more lines.

Update formatting based on changes in black.

---

setup.py

We need to make some changes to work with celery 5.  drf-yasg needs to make changes to work with drf 3.12.

Pin celery and djangorestframework.

---

rgd/core/tasks.py
rgd/geodata/models/common.py
rgd/geodata/models/fmv/etl.py
rgd/geodata/models/geometry/etl.py
rgd/geodata/models/imagery/etl.py
rgd/utility.py

S3FileField behaves exactly the same as FileField once files have been uploaded.
For more information on how to use FieldFile and File objects, see: https://docs.djangoproject.com/en/3.1/topics/files/#the-file-object for more

Remove some unnecessary usage of _field_file_to_local_path

---

Procfile
README.md
docker-compose.override.yml
rgd/core/migrations/0001_default_site.py
rgd/core/migrations/0003_merge_default_site.py
rgd/settings.py
rgd/urls.py
setup.py
terraform/main.tf
tox.ini

https://github.com/girder/cookiecutter-django-girder/releases/tag/v0.7
https://github.com/girder/cookiecutter-django-girder/releases/tag/v0.8

Backport changes from cookiecutter-django-girder v0.7 and v0.8

---

rgd/geodata/models/imagery/etl.py

Fixes a minor issue I noticed with Keypoint/Line annotations from KWCOCO

Save annotation after updates are made

---

rgd/geodata/actions.py
rgd/geodata/admin.py

Another admin action to make life easier when creating rasters of individual files.

Add another admin action

---

rgd/geodata/models/imagery/base.py
rgd/geodata/models/imagery/etl.py
rgd/geodata/templates/geodata/rasterentry_detail.html
rgd/geodata/views.py

Follow up to #197. This fixes some front-end and minor ETL issues I left behind

Follow up #197: fix front-end issues

---

rgd/geodata/templates/geodata/raster_entries.html
rgd/geodata/views.py

The front end view for search rasters was broken. This fixes that.

Fix raster search

---

rgd/geodata/templates/geodata/_includes/empty_viewer.html

Resolve #206 
For future reference, options listed here: https://github.com/OpenGeoscience/geojs/blob/a1ab530d973452a54a84d6b0a37a085df7aefd34/src/osmLayer.js#L141-L190

Add basemap choice dialog

---

rgd/geodata/models/imagery/subsample.py

Fix COG conversion options

---

rgd/geodata/models/imagery/etl.py
rgd/geodata/tests/test_imagery.py

Minor bugfix where resaving a `KWCOCOarchive` would leave orphaned `ImageFile`s

Fix issue cleaning up ImageFiles on KWCOCOArchive save

---

rgd/geodata/filters.py

I realized I had never pushed this up. This PR fixes some bugs in the facet search filter.

Facet search fixes

---

rgd/geodata/filters.py
rgd/geodata/tests/test_filters.py

Follow up to #208
I am performing manual testing of the `SpatialEntryFilter` to make sure everything is in working order.
I am hoping to add some basic tests for this as well

adjustments to SpatialEntryFilter

---

rgd/geodata/admin.py

Fix admin form for ChecksumFile

---

rgd/geodata/templates/geodata/fmventry_detail.html
rgd/geodata/views.py

Minor UI improvements

---

rgd/utility.py

See https://github.com/ResonantGeoData/ResonantGeoData/pull/276#discussion_r587909564

Hotfix: gracefully handle when 'minio_storage' is not installed

---

rgd/geodata/models/common.py
rgd/geodata/models/fmv/base.py
rgd/geodata/models/geometry/base.py
rgd/geodata/models/imagery/base.py
rgd/utility.py

Fixes broken data link URLs and refactor `_link_url` to remove unused arguments

Patch data link URL in admin views

---

rgd/geodata/templates/geodata/rastermetaentry_detail.html

Utilize the new thumbnail endpoint in the detail view for rasters

Add thumbnail to raster detail view

---

rgd/geodata/templates/geodata/_base/detail.html

Fixes #321
~~Sorry for the aggressive reformatting that my IDE did. Is there some VS Code plugin for styling these pages that you recommend? I am not sure if this file was auto-formatted before.~~
EDIT: Answered my own question, the Django extension handles this nicely. I fixed the formatting issues.

Allow copying GeoJSON to clipboard

---

rgd/geodata/management/commands/wasabi.py

This adds a shorter WASABI FMV video as the original one was quite large and would take a while to process.

Add shorter WASABI FMV video

---

rgd/geodata/actions.py
rgd/geodata/admin.py

Additional admin interface features

Add admin actions to more easily clean up entries

---

rgd/geodata/tests/test_client.py
rgdc/rgdc/version.py

Match app and client versions

---

rgdc/setup.py

Add URL to rgdc setup.py

---

rgd/geodata/filters.py

Remove rastermetaentry created check in acquisition_date filter

---

rgd/geodata/templates/geodata/_includes/empty_viewer.html

Tile layer needed to be turned off when not being used

BUG: Fix unused tile layer

---

rgd/geodata/admin.py
rgd/geodata/models/imagery/base.py

Adds admin filters to all of the model admins. e.g.:
and makes the filters more useful where they already existed

Add more admin filters

---

terraform/watch.tf

One of the records may have been wrong. this updates it

Update watch subdomain records

---

rgd/geodata/management/commands/whitelist_email.py

Prevent duplicate whitelisted emails in command

---

rgd/geodata/permissions.py
rgd/geodata/templates/geodata/_includes/empty_viewer.html
rgd/geodata/views.py

Maybe helps with #413 and patches a server error when showing the stats page with empty results

Patch permissions and stats view

---

rgd/geodata/templates/geodata/_includes/search_fields.html

Change default predicate in form and add help link

---

rgd/geodata/models/common.py
rgd/geodata/models/imagery/etl.py
rgd/geodata/models/imagery/subsample.py
rgd/utility.py

This adds support for `s://` file URLs. This assumes the instance running RGD is configured with AWS credentials.

vsis3 support

---

rgdc/rgdc/rgdc.py

Closes #434
While this implementation is simple, I'm having a tough time testing the full functionality of the endpoint (500 errors), perhaps due to the test data I'm using or my local setup. @banesullivan are you able to verify this functionality?

Add create_raster_stac method

---

django-rgd-imagery/rgd_imagery/management/commands/_data_helper.py
django-rgd-imagery/rgd_imagery/models/__init__.py
django-rgd-imagery/rgd_imagery/models/utility.py
django-rgd-imagery/rgd_imagery/serializers.py
django-rgd-imagery/tests/test_stac.py

Ensure STAC create prevents duplicate data

---

rgd-client/README.md
rgd-client/rgd_client/utils.py

Resolve https://github.com/ResonantGeoData/ResonantGeoData/issues/377

Add STAC docs in client README

---

django-rgd-imagery/rgd_imagery/serializers/stac.py

Hacky fix #464
This prevents duplicate band names and if there is only one band per file, it uses the file name as the band name.
Example result:
```
ssets": {
"image-55": {
"href": "https://s3-us-west-2.amazonaws.com/landsat-pds/c1/L8/029/041/LC08_L1TP_029041_20200105_20200105_01_RT/LC08_L1TP_029041_20200105_20200105_01_RT_B4.TIF",
"title": "LC08_L1TP_029041_20200105_20200105_01_RT_B4.TIF",
"eo:bands": [
{
"name": "LC08_L1TP_029041_20200105_20200105_01_RT_B4.TIF"
}
],
"roles": [
"data"
]
},
"image-56": {
"href": "https://s3-us-west-2.amazonaws.com/landsat-pds/c1/L8/029/041/LC08_L1TP_029041_20200105_20200105_01_RT/LC08_L1TP_029041_20200105_20200105_01_RT_B3.TIF",
"title": "LC08_L1TP_029041_20200105_20200105_01_RT_B3.TIF",
"eo:bands": [
{
"name": …
```

Hacky fix to band names in STAC serializer

---

django-rgd/rgd/filters.py
django-rgd/rgd/templates/rgd/_include/search_fields.html
django-rgd/tests/test_filters.py
rgd-client/rgd_client/rgdc.py
rgd-client/rgd_client/utils.py
testing-utils/rgd_testing_utils/data_fixtures.py

Resolve #357 
- Added test in `test_filters.py` for time of day

time of day filter

---

django-rgd-imagery/rgd_imagery/admin/base.py

fix inline geo admin widget

---

django-rgd-fmv/rgd_fmv/admin/fmv.py
django-rgd-geometry/rgd_geometry/admin/geometry.py
django-rgd-imagery/rgd_imagery/admin/base.py
django-rgd/rgd/admin/mixins.py

Follow up to #469 to use with other model inlines

Abstract geo admin inline patch from #469

---

docker-compose.override.yml
docker-compose.yml

I noticed some issues when setting up my development environment. This PR addresses two issues in the docker-compose configurations:
- fixes for the [recent flower Docker changes](https://github.com/mher/flower/pull/1121)
- fixes for the [new MinIO configuration options](https://github.com/minio/minio/pull/11185)

Docker fixes

---

django-rgd-imagery/rgd_imagery/templates/rgd_imagery/imagesetspatial_detail.html

Split the image and band settings into two different select dropdowns.

Improve image set previewer

---

django-rgd-imagery/rgd_imagery/templates/rgd_imagery/rastermeta_detail.html

Same as #515 but for the raster detail view.

Improve raster detail view ui

---

django-rgd/setup.py

Free pooch

---

docker-compose.yml

Update per https://github.com/girder/cookiecutter-girder-4/pull/157

Update MinIO ports

---

django-rgd/rgd/templates/rgd/_include/empty_viewer.html

Changes the baseMap dropdown to be dynamically filled from geo.osmLayer.tileSources

makes basemap dropdown dynamic

---

example_project/rgd_example/__init__.py
example_project/rgd_example/celery.py

Fix celery config in example project

---

django-rgd/tests/test_client.py

Adds test that instantiates a new rgd_client with the `save` option set, and then verifies the API key was correctly saved to `~/.rgd/token`.
Addresses #563 partially (still have to look into adding the MacOS CI runner)

Add test for saving an API key

---

django-rgd-3d/rgd_3d/rest/viewsets.py
django-rgd-imagery/rgd_imagery/rest/viewsets.py
django-rgd/rgd/rest/download.py
django-rgd/rgd/rest/viewsets.py
django-rgd/rgd/urls.py
django-rgd/tests/test_rest.py

Resolve #569 by just removing the endpoint

Remove generic status endpoint

---

django-rgd/rgd/utility.py

Add note to patch_internal_presign

---

django-rgd-imagery/rgd_imagery/large_image_utilities.py
django-rgd/client/PLUGINS.md
django-rgd/rgd/models/file.py
django-rgd/rgd/models/utils.py
django-rgd/rgd/utility.py
tox.ini

Cache single ChecksumFiles under a directory

---

django-rgd-3d/rgd_3d/management/commands/rgd_3d_demo.py
django-rgd-fmv/rgd_fmv/management/commands/_data_helper.py
django-rgd-fmv/rgd_fmv/management/commands/rgd_fmv_demo.py
django-rgd-fmv/rgd_fmv/tasks/etl.py
django-rgd-geometry/rgd_geometry/management/commands/rgd_geometry_demo.py
django-rgd-geometry/rgd_geometry/tasks/etl.py
django-rgd-imagery/rgd_imagery/serializers/processed.py
django-rgd-imagery/rgd_imagery/tasks/kwcoco_etl.py
django-rgd-imagery/rgd_imagery/tasks/subsample.py
django-rgd/client/rgd_client/client.py
django-rgd/rgd/configuration/configuration.py
django-rgd/rgd/management/commands/_data_helper.py
django-rgd/rgd/models/common.py
django-rgd/rgd/models/file.py
django-rgd/rgd/utility.py

- Remove unused loggers
- Use more appropriate logging levels
- Add an `rgd` logger for the `DEBUG` level during development

Better logging

---

django-rgd/setup.py

Pin django~=3.2

---

django-rgd-imagery/rgd_imagery/stac/tests.py

The tested number of queries went down once all the work was merged together.

Update number of queries

---

django-rgd-3d/tests/conftest.py
django-rgd-3d/tests/test_project/urls.py
django-rgd-3d/tests/test_rest.py
django-rgd-fmv/tests/conftest.py
django-rgd-fmv/tests/test_project/urls.py
django-rgd-fmv/tests/test_rest.py
django-rgd-geometry/tests/conftest.py
django-rgd-geometry/tests/test_project/urls.py
django-rgd-geometry/tests/test_rest.py
django-rgd-imagery/tests/test_project/urls.py
django-rgd-imagery/tests/test_rest.py
django-rgd/rgd/serializers.py
django-rgd/tests/test_project/urls.py
django-rgd/tests/test_rest.py

https://github.com/ResonantGeoData/ResonantGeoData/pull/611 introduced an error when rendering the OpenAPI spec. This PR tests for this error and fixes it.

Fix swagger error

---

django-rgd-3d/rgd_3d/admin/mesh.py
django-rgd-fmv/rgd_fmv/admin/fmv.py
django-rgd-geometry/rgd_geometry/admin/geometry.py
django-rgd-imagery/rgd_imagery/admin/annotation.py
django-rgd-imagery/rgd_imagery/admin/base.py
django-rgd-imagery/rgd_imagery/admin/processed.py
django-rgd-imagery/rgd_imagery/admin/raster.py
django-rgd/rgd/admin/common.py

Fixes issues with ForeignKey fields to ChecksumFiles taking ages to load in the dropdown menus.
Also cleans up the raster admin view

Significant usability improvements to admin views

---

django-rgd/client/rgd_client/client.py
django-rgd/tests/test_client.py

Client bug fixes

---

django-rgd-imagery/client/rgd_imagery_client/plugin.py
django-rgd-imagery/rgd_imagery/models/base.py
django-rgd-imagery/rgd_imagery/rest/viewsets.py
django-rgd-imagery/tests/test_client.py

Resolve #641 and update raster endpoint

Fix get_raster(stac=True)

---

django-rgd-imagery/rgd_imagery/stac/serializers/item/__init__.py

HOTFIX crs for STAC serializer

---

django-rgd/client/rgd_client/plugin.py
django-rgd/client/rgd_client/utils.py
django-rgd/tests/test_client.py

To avoid having to deal with merge conflicts, I based this on the branch of #648.

Python client: add method for downloading checksum files

---

django-rgd-imagery/client/rgd_imagery_client/plugin.py
django-rgd-imagery/rgd_imagery/rest/viewsets.py
django-rgd-imagery/rgd_imagery/stac/__init__.py

Resolve #669
cc @loulawrence, this is for https://github.com/ResonantGeoData/RGD-Vue/issues/82
This also fixes some broken/missing endpoints in imagery

Implement STAC Item endpoint for Raster

---

django-rgd/rgd/models/file.py
django-rgd/tests/test_download.py

Fixes #666.
Also adds test parameters to existing `yield_checksumfiles` that exercise this edge case.

Fix `yield_checksumfiles` bug

---

django-rgd/rgd/utility.py
django-rgd/tests/test_checksumfile.py

Add `file://` URL schema support

---

django-rgd-imagery/rgd_imagery/serializers/processed.py

Fix typo: validate_source_image -> validate_source_images

---

django-rgd-imagery/client/rgd_imagery_client/plugin.py
django-rgd-imagery/rgd_imagery/models/raster.py
django-rgd-imagery/rgd_imagery/rest/viewsets.py
django-rgd-imagery/rgd_imagery/serializers/raster.py
django-rgd-imagery/rgd_imagery/urls.py
django-rgd-imagery/tests/test_client.py
django-rgd/rgd/rest/mixins.py
docker-compose.override.yml
docker-compose.yml

Fix raster inconsistencies in Python client and endpoints

---

django-rgd-3d/rgd_3d/rest/viewsets.py
django-rgd-imagery/rgd_imagery/rest/viewsets.py
django-rgd-imagery/tests/test_rest.py
django-rgd/rgd/rest/viewsets.py
django-rgd/rgd/utility.py
django-rgd/tests/test_rest.py

Return URL string instead of redirecting for Images with URL-based ChecksumFiles

---

django-rgd-3d/rgd_3d/templates/rgd_3d/mesh3d_list.html
django-rgd-3d/rgd_3d/urls.py
django-rgd-3d/rgd_3d/views.py

Mesh3D ListView

---

django-rgd-fmv/rgd_fmv/rest/viewsets.py
django-rgd-fmv/rgd_fmv/urls.py
django-rgd-fmv/rgd_fmv/views.py
django-rgd-fmv/tests/test_rest.py
django-rgd/tests/test_client_plugins.py

Resolve #754 and resolve #755
Fixes the endpoints:

Patch FMV endpoints and view

---

version.py

This PR will allow a tag on `main`. That'll publish the new package nicely.

Update version file to 0.3.8
