ResonantGeoData/ResonantGeoData

core/admin.py

For over 10kb, I do noticed that the new line between "The output is too large to display in the browser."
and "Only the last {maxlen} characters are displayed" disappeared, should I add it back or it doesn't matter?

Align the log output

---

core/tasks.py
setup.py
utils/Dockerfile-urban
utils/build.sh

If there are available GPUs, this adds the --gpus flag to the docker run command.
Like in girder worker, we could check if we think it needs GPUs based on the docker image labels having nvidia information.  Otherwise, we need some way to know if we need a GPU worker, and, if so, how many GPUs are required.

Run docker with --gpus flag.

---

core/admin.py

Override docker_image_id and data_mimetype in formfield
I cannot find a way to override default textarea for fail_reason when it is empty.

Override default textarea to text input

---

README.md
core/tasks.py
docker-compose.override.native.yml
docker-compose.override.yml
docker-compose.yml

Some of our tasks run docker commands.  To do this within a docker container, it is necessary to mount the docker command and the docker socket.  This uses the default locations of each of these as deployed in ubuntu.
Further, one of the virtues of developing with docker is network separation.  However, since the ports were specified in the docker-compose.yml file, this wasn't full possible -- the docker development environment has no need to expose these to the host computer, and if the host already had one these ports in use it would fail.  This moves the port exposure to `docker-compose.override.native.yml`, and the instructions for using the native python have changed appropriately.

This allows using a docker-based worker.

---

core/admin.py
core/urls.py
core/views.py

The download url for dockerized minio includes the docker internal network name and port (e.g., starting with `http://minio:9000/`).  DNS should not be expected to resolve this, not should forwarding that port be needed for development.
This adds an api endpoint (`/api/download/<snake_case_model>/<id>/<field>`) which will download any FieldFile record in a core model.  The download is provided with the internal name of the file and, if known, a stored mimetype.
The download_file function is probably too open (though we should only load models based on some user authorization).  The explicit check for `//minio:` is ugly and brittle.
**Note**: I view this as the *wrong* way to fix downloading from minio, but I'm not sure of a better way to do it that actually works in our typical …

Allow downloading files from dockerized minio.

---

core/models.py
core/tasks.py
docker-compose.override.yml

When the worker is NOT a docker container, we can run a scoring algorithm, but when it IS a docker container, it fails.
Specifically, a scoring algorithm has two inputs: the output of an algorithm and the groundtruth.  We run a scoring algorithm via `docker run`.  The algorithm output is passed on stdin, the groundtruth is mounted as a file with the path `/groundtruth.dat`.  The scoring results are on stdout and logs on stderr.
When we are storing data on minio, the algorithm results and groundtruth are moved to local files via `_field_file_to_local_path`.  These are in the `/tmp` directory.  However, when we run a docker from within a docker, those `/tmp` paths are inside the worker docker container, and the scorer docker container can't reach them, even with a volume mount.
The solution …

Fix running scoring algorithms in docker deployment.

---

rgd/settings.py

This allows registration to work until email sending is configured in production.

Make email confirmation optional

---

README.md
dev/.env.docker-compose-native.sh

@brianhelba, you may want to quickly double-check this.
The install instructions needed some corrections.
It had been a while since I had tried to launch the site directly (I have been working in a separate toy project to build the `geodata` app) and I ran into very minor issues which are fixed here.
`.env.docker-compose-native.sh` wasn't compatible with my system (I'm using `zsh` on Mac) so I changed it to export each variable rather than iterating over a string of variables (I don't know how that originally worked, that format was strange to me. Now it is more explicit)

Update development instructions

---

docker-compose.yml

On my local system, RabbitMQ was using 60+ GB in this volume.  Preserving state doesn't seem to be useful, so this is just wasted space.

Don't use a volume for the rabbitmq container.

---

dev/init-minio.sh

Either the mc command has changed or somehow this never worked.  The initial mc command that shows help reports an error code, and thus other mc commands would not execute.  This lets that pass.

Fix initializing minio docker.

---

.gitignore

This makes it more convenient for me to override docker-compose settings using a command like `docker-compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.local.yml up`.

Update gitignore to include a local config file.

---

tox.ini

Tox generally expects tests to be run with names like "py38" not "test".  If that is done, then the basepython is automatically extracted from the environment.  Specifying the basepython allows tox to run successfully in a multi-python environment.

Set the basepython for tox.

---

setup.py

Originally we were only getting GDAL to get the library files.  At some point we started using it directly, so it belongs in setup.py (not just requirements.txt -- we still need that to properly deploy on Heroku).

Add GDAL to install_requires.

---

rgd/settings.py

I've been experimenting with a template override for drf-yasg.  The refactor to using `django-girders` for compositing config changed the app import order, breaking this.  This fixes it.  Generally, our local apps have to be installed before any app where we want to override a template (assuming we use `APP_DIRS: True` with templates).
For reference, my template override is some CSS styling to make the swagger page more compact.  This makes for better screen shots.  If others are interested in the more compact CSS, I can check that in as a different PR.

Change app import order to allow template overrides.

---

geodata/models/geometry/transform.py
geodata/models/raster/reader.py
geodata/search.py
geodata/templates/geodata/raster_entries.html
geodata/views.py
setup.py

This also fixes some coordinate transform issues.  This requires upgrading to django 3.1 (which is currently in rc1, and is not
official).  Unfortunately, there is definitely code in djangorestframework with will fail in django 3.1 until drf has a new release.
Specifically, there is ambiguity in how django 3.0 handles GDAL 3 transforms.  Compounding the problem, rasterio is bundled with a GDAL 2.x library.  Django should be using our more complete GDAL 3 library, but depending on the import order of rasterio and osgeo, rasterio may not emit wkt coordinates in a consistent manner.

Implement an initial simple raster search and display.

---

core/tests/conftest.py
core/tests/factories.py
geodata/tests/conftest.py
geodata/tests/factories.py

This removes the use of pytest_factorboy's @factory decorator as a matter of policy, as it's too fragile. Factories must be explicitly imported (if they are defined elsewhere) and registered in conftest.py.
The register function / decorator works by defining a new fixture function into the local Python file namespace. Pytest only automatically detects and registers global fixtures if they are within the namespace of conftest.py; fixtures defined as part of an import of other files are not registered.

Make test factory registration less fragile

---

core/models.py
core/urls.py
core/views.py
geodata/search.py
geodata/views.py
rgd/urls.py

Some swagger clients show summaries or descriptions rather than the endpoint as the primary menu item.  As such, make sure these are populated.
We should always populate the `operation_summary` if we specify an `operation_description` in `swagger_auto_schema`.
If we add model __doc__ strings, when we auto-generate views to generate swagger API, the first line become the summary and the rest of the docstring becomes the description.

Improve swagger descriptions.

---

rgd/settings.py

S3FF should now respect the MINIO_STORAGE_MEDIA_URL setting:
https://github.com/girder/django-s3-file-field/blob/master/s3_file_field/constants.py#L65-L72

Remove the workaround for disabling S3FF in development

---

core/urls.py
rgd/urls.py

This is deprecrated by Django 3.1.
Also fix imports of the "include" function to use the canonical location.

Remove imports of deprecated "django.conf.urls.url"

---

core/templates/base.html
geodata/search.py
geodata/templates/geodata/_includes/point_search.html
geodata/templates/geodata/_includes/viewer.html
geodata/templates/geodata/raster_entries.html
geodata/templates/geodata/spatial_entries.html
geodata/urls.py
geodata/views.py

This makes the viewer reusable. My goal in doing this is to give us one single viewer that we can place on any page and it will automatically display the search parameters and data footprints that are loaded from the page's context
This will enable us to more easily define any type of seach-by page for any model. I am doing this to have a search page for FMV over in #143 
Currently, this assumes the search parameters are a single point but when we add other search parameters, we can update this to handle those cases.

Make search viewer reusable

---

dev/django.Dockerfile
requirements.txt
runtime.txt

Only install pytorch for CPU.
Heroku has a limit to how many packages can be installed, set to a compressed size of 500 MB.  Pytorch alone, by default, takes around 750 Mb.  By using the cpu-only version we are below but still close to the limit.

Fix Heroku deployment.

---

rgd/geodata/models/common.py

Before, this ends up with a hash-prefix from minio.  This just uses the basename.

Improve the default name for files.

---

utils/Dockerfile-kwiver-dump-klv

I updated the Kwiver docker image used for extracting the KLV metadata in the FMV datasets to use the latest release of Kwiver rather than a custom build.
(this has already been pushed to Dockerhub)

Update Kwiver Dockerfile

---

rgd/core/static/css/style.css
rgd/core/templates/base.html

The recent file reorganization resulted in the Bulma CSS file being excluded. Rather than re-adding it to the repo, it's more maintainable to load it from a CDN.

Load Bulma from a CDN, instead of vendoring it in the repo

---

dev/django.Dockerfile
docker-compose.override.yml
docker-compose.yml

https://github.com/girder/cookiecutter-django-girder/releases/tag/v0.3

Backport changes from cookiecutter-django-girder v0.3

---

setup.py

This is in anticipation of an upcoming `django-s3-file-field` release, which may introduce breakages.

Pin django-s3-file-field

---

requirements.txt
setup.py

Jon Crall recently released a new version of `kwimage` and `kwarray` that makes `torch` and `pandas` optional dependencies. These changes should leverage that and significantly decrease the size of the virtual environment deployed on Heroku

Bump kwimage to remove torch dependency

---

rgd/geodata/templates/geodata/fmventry_detail.html

This is a minor change to move the FMV video onto the GeoJS map's UI layer.
We cannot display the video over the red marker because it is a polygon. AFAIK, only quads support overlain video -- we cannot use a quad here because the video frame's projection on the ground is typically a trapezoid

Move video inside map UI layer for FMV detail page

---

rgd/geodata/api/__init__.py
rgd/geodata/api/download.py
rgd/geodata/api/search.py
rgd/geodata/filters.py
rgd/geodata/search.py
rgd/geodata/urls.py
rgd/geodata/views.py

This simply adds the [django-filter](https://django-filter.readthedocs.io/en/stable/) based faceted search API endpoint at `api/geodata/search`.
- `q`: geometry (sorts sets by NN)
- `predicate`: DE-9IM spatial predicate
- `relates`: DE-9IM string
- `distance` (min/max)
- `acquired` (min/max)
- `created` (min/max)
- `modified` (min/max)
- `datatype`: choice of raster, geometry, or FMV
- `instrumentation` (search with `icontains`)
- `num_bands` (min/max)
- `resolution` (min/max)
- `frame_rate` (min/max)
I can see a way where this could replace the [`search.py`](https://github.com/ResonantGeoData/ResonantGeoData/blob/master/rgd/geodata/search.py) module entirely. I had been working on implementing the GUI for this, but the code duplication was getting a bit out of hand. Instead, I am working …

Add faceted search

---

rgd/core/static/css/style.css

Resolve #210: I believe this should do it.
https://github.com/ResonantGeoData/ResonantGeoData/issues/210#issuecomment-744507473 outlines that this file is throwing the error as it is looking for stylesheets that do not exist. Upon inspection, this file isn't even needed as the templates in the `core` app pull `style.css` which should pull from `geodata` since that app is set up correctly.
Also, the `core` app is entirely disabled on the frontend so we shouldn't need any static resources for it.

Remove unused style

---

rgd/geodata/admin.py
rgd/geodata/serializers.py
rgd/geodata/tests/test_api.py
tox.ini

Resolve #229 
The `SubsampledImageSerializer` now checks the DB for existing entries with the same sample parameters and returns the first match if one exists rather than creating a duplicate.
It also triggers a save event to reprocess the subsampling

Prevent duplicate SubsampledImage models on POST

---

rgd/geodata/management/commands/demo_data.py
rgd/geodata/models/fmv/etl.py
rgd/geodata/models/geometry/etl.py
rgd/geodata/models/imagery/etl.py
rgd/geodata/models/imagery/subsample.py
rgd/geodata/serializers.py
rgd/utility.py

Quick patch to make code cleaner/better and use functionality already exists in django
Follow up to #236 
-----
While I was at it, I cleaned up a few other places in the ETL routines where this logic was used and added a new `get_or_create_no_commit` helper for doing the same thing without automatically saving to the DB.

Use get_or_create in serializer

---

rgd/geodata/tests/test_api.py
rgd/geodata/tests/test_search.py

Patch for https://github.com/girder/django-composed-configuration/pull/109
This changes the two tests hitting the POST endpoint to use an authenticated API client.
@brianhelba: for endpoints that are read-only, should we be using [`api_client` here](https://github.com/ResonantGeoData/ResonantGeoData/blob/87ba08fd261c34940d615c1f0e13874dc333e487/rgd/geodata/tests/conftest.py#L12) over the default `client` fixture (presumably coming from `pytest-django`... or where is that actually coming from?)?

Use authenticated API client

---

rgd/geodata/api/download.py
rgd/geodata/api/search.py

DRF's "Response" class handles the details of content negotation and JSON encoding. It should almost always be used as the return value of API endpoints. See: https://www.django-rest-framework.org/api-guide/responses/

Return DRF Response objects in API endpoints

---

rgd/core/urls.py
rgd/core/views.py
rgd/geodata/api/download.py
rgd/geodata/tests/test_api.py
rgd/geodata/tests/test_search.py
rgd/geodata/urls.py

This improves 2 things:
* Use `response.data` instead of `json.loads(response.content)`. This still ensures that the DRF Serializers are invoked to serialize Model representations into primitive Python data structures, but avoids the code and performance overhead of encoding / decoding a JSON string. See: https://www.django-rest-framework.org/api-guide/testing/#checking-the-response-data (see #252)
* Perform each assert on its own line, which is syntactically necessary. Additional expressions to an `assert` statement are not interprepted as additional assertions to be made, but rather as the arguments (such as a failure message) to the `AssertionError` that a failure raises. See: https://docs.python.org/3/reference/simple_stmts.html#grammar-token-assert-stmt

Improve examination of HTTP response data in testing

---

rgd/settings.py
setup.py

This adds support for the latest release of `django-composed-configuration`.

Ensure local templates are still loaded first

---

rgd/geodata/models/imagery/base.py
rgd/geodata/tests/test_api.py

Fixes an issue causing tests to fail across PRs. The post request was double encoding a `JSONField`

PATCH: fix JSONField double encoding in test

---

rgd/geodata/templates/geodata/_base/base.html
rgd/geodata/templates/geodata/_includes/empty_viewer.html
rgd/geodata/templates/geodata/_includes/search_form.html

The base map and search fields would reset anytime the page reloads (necessary because we are using server-rendered pages). These changes add cookies to the site to set the search field and preferred base map so that they stay consistent across pages
| `master` | this branch |
|---|---|
| ![2021-02-01 20 24 22](https://user-images.githubusercontent.com/22067021/106548135-b4d61600-64cb-11eb-81e5-698c2266d578.gif) |  ![2021-02-01 20 24 01](https://user-images.githubusercontent.com/22067021/106548141-ba336080-64cb-11eb-819d-c00397291803.gif) |
Since these cookies have to do with UI elements and not the Django view, I went with a classic cookies approach rather than Django's tooling to set cookies.
It's a bit crude but it works until we make the switch to a single page app with Vue
Todo

Use cookies to improve UI across page reloads

---

rgd/geodata/templates/geodata/_base/detail.html

Simple back button to the detail page UI
This is a simple solution before we make the switch to a single page app

Add basic back button to detail view

---

docker-compose.override.yml

Now flower is exposed for monitoring tasks at: http://localhost:5555/flower/dashboard

Expose flower via docker-compose

---

rgd/geodata/api/tiles.py
rgd/geodata/models/common.py

@mcovalt, is it okay to move `patch_internal_presign` into `get_url` directly? Sometimes we need the minio URL if doing FUSE and not VFS
Also I renamed `get_local_vsi_path()` to `get_vsi_path()` as this should work in any environment

Move patch_internal_presign

---

.circleci/config.yml

This moves the tests and linting into their own steps on CircleCI so it's easier to see what's going on/why a build failed
| `master` | this branch |
|---|---|
| <img width="1192" alt="Screen Shot 2021-03-05 at 12 08 08 PM" src="https://user-images.githubusercontent.com/22067021/110162068-76be6180-7dab-11eb-88eb-ebb02c3a071f.png"> | <img width="1201" alt="Screen Shot 2021-03-05 at 12 07 31 PM" src="https://user-images.githubusercontent.com/22067021/110162019-60180a80-7dab-11eb-984e-6068470e62ee.png"> |

[CI] Move linting to its own step

---

rgd/geodata/management/commands/_data_helper.py
rgd/geodata/models/imagery/etl.py

Quick patch for #297 
This resolves the issue, but I want to keep #297 open until we have a better way to handle the `skip_signal` functionality to prevent typos like this from happening again

Fix skip_signal typo

---

rgd/geodata/management/commands/_data_helper.py

This resolves #297
The issue was that `get_or_create` was committing the entry to the DB triggering a `save` call triggering the tasks and then we were running the ETL routine again after that causing the duplicate key error

Resolve duplicated tasks in demo commands

---

rgd/geodata/management/commands/_data_helper.py
rgd/geodata/models/common.py
rgd/utility.py

Previously when adding a remote file (via just an URL) the `name` field on the model would be improperly populated when dealing with a direct download link becaue it naively used `os.path.basename` on the URL.
These changes use features of `urlopen` to inspect the file at the link and fetch its name.
For the file at this url, `https://data.kitware.com/api/v1/file/604a547c2fa25629b93176d2/download` we see the following names:
| `master` | this branch |
|---|---|
|`download` | `20151007_063901_dstoMX20HD__EON_High_012_298-520_600-280.mpg`|
This PR also wraps `urlopen` in a context manager to make sure we close it when we're done looking at a file

Add contextmanager around urlopen and use to get remote file names

---

rgd/settings.py

This is to allow for the python client (#178) to authenticate to the server.

Add Basic Auth

---

rgd/geodata/urls.py

We had the base URL redirecting to `geodata/spatial_entries/`. This removes that and puts the spatial entries list view/search page as the homepage.

Fix index URL redirect

---

rgd/geodata/templates/geodata/_base/detail.html
rgd/geodata/templates/geodata/rastermetaentry_detail.html

Hides the Copy GeoJSON button per https://github.com/ResonantGeoData/ResonantGeoData/issues/321#issuecomment-803049118
Fixes a few minor things in the detail views

Minor fixes to detail views

---

rgd/geodata/templates/geodata/rastermetaentry_detail.html

This helps relieve some of the stress #323 is experiencing.
These changes make sure the front-end tile layer in GeoJS is not fetching empty/null tiles outside the extent of the raster. Previously, we were loading tiles for the entire map view -- they'd just be transparent if the raster had no data there. You could notice this by watching the tile requests continue in the logs after the ROI is seemingly done loading or you could change the image compression to JPEG to make null regions opaque.
For any given raster, now only the tiles intersecting the raster are fetched by GeoJS' tile layer
https://user-images.githubusercontent.com/22067021/112364614-5728a380-8c9c-11eb-9663-70c1f06c99f7.mov 
https://user-images.githubusercontent.com/22067021/112364515-382a1180-8c9c-11eb-9769-23fb9aafbb7a.mov …

Add condition to prevent loading empty tiles for rasters on frontend

---

demos/GeoData-API.ipynb
rgd/geodata/api/get.py
rgd/geodata/serializers.py
rgd/geodata/templates/geodata/rastermetaentry_detail.html
rgd/geodata/tests/test_api.py
rgd/geodata/tests/test_search.py
rgd/geodata/tests/test_tiles.py
rgd/geodata/urls.py

For #332 
Adds new serializers/endpoints to make it easier to perform a search and go straight to downloading data
This splits up the `geodata` endpoints into three new tags:
- `geodata`: for accessing models via serializer and downloading raw data
- `geosearch`: for performing searches against data in the catalog
- `geoprocess`: for performing operations on data in the catalog (e.g. subsampling, COG conversion, tiling)
I updated the demo notebook (`demos/GeoData-API.ipynb`) to show what is now possible - this is a developer's demo and not intended to be shown externally. @AlmightyYakob, this should be everything needed to proceed with #332

API Improvements

---

rgd/utility.py

Catches when a URL is not accessible because the backing FUSE lib that we use will get hung on 403's

Add check to make sure URL exists for FUSE

---

setup.py

3.2 is out, so now we should use the public (presumably stable) version. See https://www.djangoproject.com/weblog/2021/apr/06/django-32-released/

Bump Django to release version 3.2

---

setup.py

Pypi doesn't have a link to the github webpage. This fixes that.

Add url to setup.py

---

rgdc/rgdc/rgdc.py
rgdc/rgdc/utils.py

Closes #354, Supersedes #359.
This conflicts with #360, although I was unaware of this PR until now. However, I think my PR addresses slightly more use cases than that one.
Currently, this function will fetch as many results as it can from the server at once, and paginate until the user specified limit is reached. So, for example, if the user specifies a limit of 1200, this function will first just pass that limit to the server, which will only return 1000 results, since that's the silent max. This function will then fetch the remaining 200 results after that.
However, I've also considered modifying this function to always use the server default of 100, and deal with the limit solely in the client. The main reason for this would be to keep individual request times down, as for 1000 …

Add pagination to `Rgdc.search`

---

rgdc/README.md
rgdc/rgdc/rgdc.py
rgdc/rgdc/session.py
rgdc/rgdc/utils.py

This MR contains 3 small improvements to `rgdc.Rgdc`.
1. Add 5 automatic retries on all GET requests. This is to guard against random 503 errors from rate-limiting that would be fixed by simply rerunning the command. The implementation is to bake this into the `Session` object; see https://www.peterbe.com/plog/best-practice-with-retries-with-requests for the approach.
2. Add `overwrite=False` kwarg to `download_raster_entry`. This will skip files already on disk - handy for speeding up tests and making scripts idempotent.
3. Perhaps a more controversial one: let `download_raster_entry` and `download_raster_entry_thumbnail` directly parse a dict returned by `search` to find the `id`, rather than the user having to make another request manually as in the README example or study that dict to …

Rgdc usability improvements

---

.github/workflows/rgdc.yml
rgdc/README.md
rgdc/rgdc/rgdc.py

For #352: removes the `_entry` notation from the API
Resolve #349: adds a CI routine to "test" the client API and publish it to PyPI on tags

Cleanup rgdc function names

---

rgd/geodata/actions.py
rgd/geodata/admin.py
rgd/geodata/signals.py

Adds an admin user approval process for all new sign ups
This sets every user's `is_active` status to `False` on account sign-up. An admin will have to go into the admin portal and select which user to make active manually. To make this easier, I added admin actions to do this in bulk

User admin approval on sign up

---

rgdc/rgdc/rgdc.py

This adds the ability to create an authenticated client instance, without needing to specify your username/password in plain text.

Add password prompt to Rgdc class constructor

---

.github/workflows/release.yml
.github/workflows/rgdc.yml

With the previous setup, creating releases through Github wouldn't trigger the PyPI publish workflow.

Add standalone workflow for tags/releases

---

terraform/watch.tf

Fixing error on TF: https://app.terraform.io/app/ResonantGeoData/workspaces/ResonantGeoData/runs/run-o42QXWUxzrBAoVej
This is one of the zones for `us-west-2`: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-regions

Attempt fix watch subdomain

---

rgd/geodata/management/commands/_data_helper.py
rgd/geodata/management/commands/demo_data.py
rgd/geodata/management/commands/gc_catalog.py
rgd/geodata/management/commands/s3_landsat.py
rgd/geodata/models/imagery/etl.py
rgd/geodata/templates/geodata/_includes/empty_viewer.html
rgd/geodata/templates/geodata/rastermetaentry_detail.html
rgd/geodata/tests/test_imagery.py

This fixes an issue when computing the outline of rasters. Previously, the transform was done incorrectly and would lead to errors in larger images. Here is an example with Landsat imagery:
| `master` | this branch |
|---|---|
|  ![Screen Shot 2021-05-05 at 8 53 54 AM](https://user-images.githubusercontent.com/22067021/117171381-0cfd0c80-ad88-11eb-920f-48395392f2ac.png) |  ![Screen Shot 2021-05-05 at 9 56 15 AM](https://user-images.githubusercontent.com/22067021/117171576-387ff700-ad88-11eb-83ee-5045bf23bc32.png) |
Further, I am working to resolve an issue when computing the valid data mask (`footprint`) when the `nodata` is set to `None`
resolves #372

Fix outline transform for rasters

---

rgd/settings.py

See https://github.com/ResonantGeoData/ResonantGeoData/pull/365#discussion_r620865765
Defaults for `Value` are `environ=True` and `environ_prefix='DJANGO'`, so remove explicitly setting those

Cleanup after #365

---

rgd/geodata/api/get.py
rgd/geodata/serializers.py
rgd/geodata/urls.py
rgdc/rgdc/rgdc.py
setup.py

It describes the raster's 
- footprint
- bounding box
- related images
- ancillary files
- projection
E.g.:
```json
{
"type":"Feature",
"stac_version":"1.0.0-beta.2",
"id":139,
"properties":{
"proj:epsg":32618,
"proj:transform":[
499980.0,
20.0,
0.0,
4800000.0,
0.0,
-20.0
],
"datetime":"2021-05-06T18:05:45.018503Z"
},
"geometry":{
"type":"Polygon",
"coordinates":[
[
[
-75.00024679052602,
43.35285539188815
],
[
-73.6455526700249,
43.344834816006944
],
[
-73.66698539120085,
42.356322389620374
],
[
-75.00024288390158,
42.36407191996271
],
[
-75.00024679052602,
43.35285539188815
]
]
]
},
"links":[
],
"assets":{
"image-133":{
"href":"http://localhost:9000/rgd-storage/1f9254bc-ee20-4914-a944-8d04f5aee120/L1C_T18TWN_A028079_20201106T160014.tif?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=mco …
```

STAC serializer (renderer) for RasterMetaEntry

---

setup.py

Follow up to https://github.com/ResonantGeoData/ResonantGeoData/issues/307#issuecomment-797640849
We are seeing #307 again on the Heroku instance lately. Hopefully setting the min version will prevent an older large_image from being installed

Set large_image version

---

rgd/geodata/permissions.py
rgd/settings.py

Adds a new setting to give global read access to records that do not have assigned permissions. 
This is useful if we want all users to have access to all data in an instance by default and still be able to make certain collections private.

Add setting to allow access to unassigned permissions for all users

---

rgd/geodata/permissions.py
rgd/geodata/tests/conftest.py
rgd/geodata/tests/data_fixtures.py
rgd/geodata/tests/test_api.py
rgd/geodata/tests/test_filters.py
rgd/geodata/tests/test_fmv.py
rgd/geodata/tests/test_imagery.py
rgd/geodata/tests/test_permissions.py
rgd/geodata/tests/test_tiles.py

This resolves #410 by adding a `distinct()` call to the filterset and also adds a new test to verify all is working.
Further, I noticed we were re-using a lot of the same data fixtures in different testing modules so I went ahead and moved many of them to a new `data_fixtures` module

Fix duplicate search results from permissions

---

rgd/geodata/models/imagery/etl.py

Whoops 🙃 
This makes sure we compute a reasonable polygon -- especially in the case of Landsat 7 ETM images with the scan line error
| before | after |
|---|---|
| ![Screen Shot 2021-06-02 at 9 33 10 AM](https://user-images.githubusercontent.com/22067021/120511258-7b34ef00-c387-11eb-9b77-787e83449340.png) | ![Screen Shot 2021-06-02 at 9 35 24 AM](https://user-images.githubusercontent.com/22067021/120511276-825bfd00-c387-11eb-9243-be371ace0ba2.png) |

Fix Convex Hull of valid data footprint

---

terraform/watch.tf
terraform/watch_dev.tf

These resources were created manually, but have been imported into the TF state to ensure they get cleaned up.

Add Terraform to store watch_dev state

---

terraform/watch_dev.tf

This bug wasn't detected by the TF plan.

Add a missing TTL for aws_eip.watch_dev TF

---

DEVELOPMENT.md
tox.ini

I find it useful to have all the dependencies installed locally so I can use editor magic to follow imported symbols. Tox has a pleasant way to instantiate a development environment [documented here](https://tox.readthedocs.io/en/latest/example/devenv.html).
This PR adds a tox "testenv" that has all dependencies and documents how to use this to create a development venv.

Local tox development environment

---

django-rgd-imagery/rgd_imagery/serializers.py

The STAC serializer's create method should not trigger the raster ETL routines.
Currently we're ingesting NITF images that those ETL routines do not support so this is necessary

Fix SATC serializer create

---

django-rgd/rgd/utility.py

Catches an issue when `simple_httpfs` is installed but `libfuse` is missing

Catch libfuse missing

---

README.md
django-rgd-3d/vtkjs_viewer/src/index.js
django-rgd-fmv/rgd_fmv/tasks/etl.py
django-rgd-imagery/rgd_imagery/migrations/0001_initial.py
django-rgd-imagery/rgd_imagery/models/__init__.py
django-rgd-imagery/rgd_imagery/models/annotation.py
django-rgd-imagery/rgd_imagery/models/base.py
django-rgd-imagery/rgd_imagery/models/kwcoco.py
django-rgd-imagery/rgd_imagery/rest/tiles.py
django-rgd-imagery/rgd_imagery/tasks/etl.py
django-rgd/rgd/models/common.py
django-rgd/rgd/templates/rgd/_include/search_map.html
django-rgd/rgd/utility.py
django-rgd/tests/test_common.py
docs/ingest-data.md
tox.ini

This fixes a handful of spelling errors and implements [codespell](https://github.com/codespell-project/codespell/) in a new tox test
I did not add this to the CI tests because codespell can get quite annoying if left on its own. This is useful as a local check to find and correct spelling errors.
simply run `tox -e codespell` to check for spelling errors

Fix typos and add codespell to tox

---

django-rgd-imagery/rgd_imagery/large_image_utilities.py
django-rgd-imagery/rgd_imagery/rest/tiles.py
django-rgd-imagery/rgd_imagery/templates/rgd_imagery/rastermeta_detail.html

In support of https://github.com/ResonantGeoData/ResonantGeoData/issues/480 (GRIB data files are supported by GDAL, so we can technically treat these as rasters and preview individual bands). At present, our ETL routines are not properly extracting the spatial reference of GRIB datasets, so this doesn't work. GRIB support will come in its own PR.
This is a needed feature on its own so I'd like to land this on its own and sort of moves us toward https://github.com/ResonantGeoData/ResonantGeoData/issues/421

Support individual band selection in raster detail view

---

django-rgd-imagery/rgd_imagery/large_image_utilities.py
django-rgd-imagery/rgd_imagery/tasks/etl.py
django-rgd-imagery/setup.py
django-rgd-imagery/tests/test_imagery.py
django-rgd/rgd/templates/rgd/_include/empty_viewer.html

Resolve #480
Utilizes https://github.com/girder/large_image/pull/639/files
This improves handling of dataset bounds when they exceed the map projection's maximum bounds
This enables full support for global raster data like we see in #480 
-----

Improve raster bounds handling

---

django-rgd-imagery/rgd_imagery/rest/get.py
django-rgd-imagery/rgd_imagery/rest/post.py
django-rgd-imagery/rgd_imagery/serializers/base.py
django-rgd-imagery/rgd_imagery/serializers/raster.py
django-rgd-imagery/rgd_imagery/urls.py
django-rgd/rgd/rest/__init__.py
django-rgd/rgd/rest/get.py
django-rgd/rgd/rest/post.py
django-rgd/rgd/serializers.py
django-rgd/rgd/urls.py

Partially address #452 
This adds the POST endpoints we hope to expose in the Python client for the work in https://github.com/ResonantGeoData/RGD-ScrumBoard/issues/29
Adds new POST endpoints for (and GET when not already present):
- `Collection` and `CollectionPermission`
- `ChecksumFile` (URL files only)
- `SpatialAsset`
- `Image`
- `ImageSet`
- `ImageSetSpatial`
- `Raster`
cc @AlmightyYakob

More POST (and GET) endpoints!

---

rgd-client/rgd_client/utils.py

The previous usage of `order_datetimes` used the syntax `value1, value2 if value1 < value2 else value2, value1`, which actually will return a 3-tuple of (value1, max(value1, value2), value2) because the comma operator has lower precidence than inline if staements.
I also added a doctest with the code I used to verify that it was failing and then ensure that the fix worked. 
We should be able to get this test to run in the CI without too much trouble: Add `xdoctest` as a dependency and give `--xdoctest` as an argument to pytest. I haven't used tox in awhile, so not sure if that complicates anything.

Fix error in order_datetimes, add doctest

---

django-rgd/setup.py

Due to a change in [`pooch`](https://github.com/fatiando/pooch/issues/252), `scikit-image` is [broken](https://github.com/scikit-image/scikit-image/issues/5528) on import. This was [fixed](https://github.com/scikit-image/scikit-image/pull/5529) in `scikit-image`, but a release hasn't been cut yet. This currently breaks our tests.
The breaking change was introduced in version `1.5.0` of `pooch`, so PR restricts the version accordingly.

Pin pooch to <1.5.0

---

django-rgd-imagery/rgd_imagery/tasks/etl.py

Images are opened and checked to be rasters but that metadata is not used. This can dramatically slow down data ingest times. To speed it up, I am commenting this out.
Note that, the images could be non-geospatial and this now will not throw an error.

Stop processing unused images

---

django-rgd/README.md
django-rgd/rgd/signals.py

On some instances, like RD-OpenGeo, we may want to automatically allow users to sign up

Add setting to automatically approve user sign ups

---

django-rgd-imagery/rgd_imagery/templates/rgd_imagery/imageset_detail.html

Uses GeoJS's tile viewing capabilities to show tiles in the ImageSet detail view instead of a thumbnail.
Resolve #518

Show tiles instead of thumbnails in ImageSet detail view

---

.github/workflows/ci.yml
README.md
codecov.yml
tox.ini

Resolve #440: this finally fixes our code coverage reports and properly uploads the full report to codecov
Further, I added a step to the CI to create model graphs of each of the apps and upload those images as build artifacts. These can be useful to see when making changes to models

Upload code coverage and model graphs

---

django-rgd/setup.py

`psutil` is used in `django-rgd`, but not listed as a dependency. Recently, the CI for https://github.com/girder/Danesfield has been failing, due to missing the `psutil` module. I'm not sure what caused this to happen spontaneously, but my best guess is an upstream dep recently removed `psutil` from _it's_ dependencies.
This PR adds `psutil` to `install_requires`.

Add missing psutil dep in django-rgd setup.py

---

django-rgd-imagery/client/rgd_imagery_client/plugin.py
django-rgd/client/PLUGINS.md
django-rgd/client/rgd_client/_plugin_utils.py
django-rgd/client/rgd_client/client.py
django-rgd/client/rgd_client/plugin.py
django-rgd/tests/test_client_plugins.py

Closes #564 
This PR allows for a plugin to access a sibling plugin by defining a _plugin dependency_. In this context, a "sibling plugin" is just any plugin that's installed alongside the plugin in question. While access to all namespaced plugins was already available from the _client_, prior to this change, plugins themselves could not see other plugins.
This has the following breaking change: Plugins must now inherit from `RgdPlugin`. This both helps with plugin discovery, as well as allows for plugin dependencies to be defined.
I'm fairly happy with this solution, but please take a look and lmk if you think this approach is flawed in some way, or if you think there's a better approach.

Add support for plugin dependencies

---

django-rgd/rgd/models/file.py
django-rgd/rgd/models/utils.py
django-rgd/rgd/utility.py

Resolve #555 
This creates a new temporary directory called `file_locks` where we store all file locks to avoid any issues with downstream software not wanting/needing those lock files. After all, these files should only be used by RGD.
To do this, I am taking the hash of the checked-out file path and saving that hash as the lock file under the temporary directory.

Place FileLocks under dedicated path

---

django-rgd/client/rgd_client/client.py
django-rgd/tests/conftest.py
django-rgd/tests/test_client.py

When using an API key from `~/.rgd/token`, the client will verify the key is valid by calling a protected endpoint. If it's not, and the user also provided their username and password, the client will attempt to retrieve a new API key from the server and save it at `~/.rgd/token`.
This PR also adds a test for the new functionality and logging to clarify what's going on when an API key is invalid.
Closes #563

Retrieve new API key if the saved key is invalid

---

django-rgd-imagery/rgd_imagery/large_image_utilities.py
django-rgd-imagery/rgd_imagery/rest/tiles.py
django-rgd-imagery/rgd_imagery/tasks/subsample.py
django-rgd-imagery/rgd_imagery/templates/rgd_imagery/rastermeta_detail.html
django-rgd-imagery/setup.py
django-rgd/rgd/templates/rgd/_base/base.html

This fixes the utils/endpoints we had for extracting regions from images and adds a new interface on the raster detail view page to select an ROI within the bounds of a raster and directly download that ROI.
Some things to address:
If accessing a large dataset remotely, this will not be very RESTful . In the future (with the new SPA frontend), we should have this tool utilize the `ProcessedImage` model and do this asynchronously with polling to see if the job is done.
| UI | Produced ROI |
|---|---|
| ![Screen Shot 2021-11-14 at 6 48 26 PM](https://user-images.githubusercontent.com/22067021/141710076-9a8f643a-429d-418f-9744-b5d743486812.png) |  ![Screen Shot 2021-11-14 at 6 53 27 PM](https://user-images.githubusercontent.com/22067021/141710144-3d43d6fe-043c-45df-858a-0fae385034f0.png) |

Extract ROIs from Raster detail view

---

docker-compose.demo.yml
example_project/.gitignore
example_project/README.md
example_project/rgd_example/settings.py
example_project/setup.py

Following up from https://github.com/ResonantGeoData/RD-OpenGeo/pull/12 and #334 
This adds a docker-compose override and brief docs on how to utilize this.

Add better performance demo config

---

django-rgd-geometry/rgd_geometry/rest/viewsets.py
django-rgd-geometry/rgd_geometry/serializers.py
django-rgd-geometry/rgd_geometry/urls.py

- Adds serializer + viewset for `GeometryArchive`
- Enable POST/PUT/PATCH/DELETE operations on existing `Geometry` viewset
- @banesullivan is this correct? That viewset currently inherits from `ReadOnlyModelViewSet` which disables POST operations, but it is listed in #452 as one of the models to have POST support for.

POST endpoints for `rgd_geometry`

---

django-rgd-fmv/rgd_fmv/rest/viewsets.py
django-rgd-fmv/rgd_fmv/serializers.py
django-rgd-fmv/rgd_fmv/urls.py

Currently, `FMVMetaSerializer` is being used for general GET requests to `rgd_fmv`. However, I believe the correct behavior for a POST request is to only allow direct upload of a FMV file; it should not be allowed to modify the `FMVMeta` as that is autogenerated. That is what I implemented in this PR, but @banesullivan please correct me if I am wrong :slightly_smiling_face:

POST endpoints for `rgd_fmv`

---

django-rgd/rgd/models/file.py
django-rgd/rgd/rest/viewsets.py
django-rgd/rgd/serializers.py
django-rgd/tests/test_rest.py
testing-utils/rgd_testing_utils/factories.py

This PR adds a `tree` action, which allows for files to be searched by their name prefix. The result serves to mimic a normal folder hierarchy, returning files/folders at each level. For example, if you had the following files injested:
* `folder/a.txt`
* `folder/b.txt`
* `folder/c/d.txt`
These can be viewed as such
```
folder/
| -- a.txt
| -- b.txt
| -- c/
|    | -- d.txt
```
If you wanted to search for all files under `folder`, you would just pass `folder` to the `tree` endpoint in `path_prefix`. The result would be roughly the following
```
"folders": {
"c": {
"size": 123123,
"num_files": 1,
"created": "2021-11-05T21:23:41.498195Z",
"modified": "2021-11-05T21:23:41.498210Z"
}
},
"files": {
"a.txt": <ChecksumFile>,
"b.txt": <ChecksumFile>
}
```
And extending the path_prefix to …

Add tree action on ChecksumFile ViewSet

---

django-rgd-imagery/rgd_imagery/rest/tiles.py
django-rgd-imagery/tests/test_tiles.py
django-rgd/rgd/configuration/configuration.py

Closes #604
In order to serve a tile, information must be known about it from our database. The tile endpoint recieves many concurrent connections. As a result, the connection limit to PostgreSQL was getting exhausted.
This PR:
- Uses memcached to store session information
- Caches database queries required to serve different tiles from the same base image
- Tests that no consecutive calls to the tile endpoint will access the database

Cache tile queries

---

django-rgd-imagery/rgd_imagery/stac/serializers/item/__init__.py
django-rgd-imagery/rgd_imagery/stac/tests.py
django-rgd-imagery/rgd_imagery/stac/views.py

Viewing large collections of STAC items would take a long time. If N is the number of STAC items in a collection, 12N+1 queries were made.
This PR reduces the number of queries down to 6. The number of queries is independent of the number of STAC items in a collection.

Optimized STAC queries

---

django-rgd-fmv/rgd_fmv/serializers.py
django-rgd-geometry/rgd_geometry/serializers.py
django-rgd-imagery/rgd_imagery/serializers/raster.py
django-rgd/rgd/serializers.py

Each serializer that inherited from `SpatialEntrySerializers` would execute a SQL query when evaluated. In other words, if 10 items were requested, 10 superfulous SQL queries were made. This PR removes this behavior. It also cleans up the way the serializer works by relying on `SerializerMethodField`.

Optimized SpatialEntrySerializer and all subclasses

---

django-rgd/rgd/rest/viewsets.py

https://github.com/ResonantGeoData/ResonantGeoData/pull/611 unexpectedly broke a test. This is a hotfix to fix it.

Select subclasses for SpatialEntry viewset

---

django-rgd-fmv/rgd_fmv/views.py
django-rgd-geometry/rgd_geometry/views.py
django-rgd-imagery/rgd_imagery/views.py
django-rgd/rgd/permissions.py
django-rgd/rgd/views.py

This causes the permissions query to use a union of inner joins which is much more performant than the left joins it defaulted to. It also cleans up the views.

Use inner joins for the permissions query

---

django-rgd-imagery/rgd_imagery/templates/rgd_imagery/imageset_detail.html

Follow up to #523 to enable bigger zoom range when viewer non-geospatial images. Needed for demo ASAP... if this isn't the right way, we can fix later

Need full zooming on image set viewer

---

django-rgd/rgd/permissions.py
django-rgd/tests/test_permissions.py

Address issue mentioned in #612 
There is an issue filtering on `Collection`s with `RGD_GLOBAL_READ_ACCESS` enabled. This test highlights the issue:
```
@pytest.mark.django_db(transaction=True)
def test_unassigned_permissions_complex(
user_factory, user, spatial_asset_a, spatial_asset_b, settings
):
settings.RGD_GLOBAL_READ_ACCESS = False
admin = user_factory(is_superuser=True)
admin_q = filter_read_perm(admin, models.SpatialEntry.objects.all())
basic_q = filter_read_perm(user, models.SpatialEntry.objects.all())
assert len(admin_q) == 2
assert len(basic_q) == 0
admin_q = filter_read_perm(admin, models.Collection.objects.all())
basic_q = filter_read_perm(user, models.Collection.objects.all())
assert len(admin_q) == 2
assert len(basic_q) == 0
settings.RGD_GLOBAL_READ_ACCESS = True
admin_q = …
```

Test RGD_GLOBAL_READ_ACCESS for Collections

---

django-rgd/rgd/views.py

https://github.com/ResonantGeoData/ResonantGeoData/pull/619 changed the bahavior of the homepage by showing all polygons instead of just the paginated ones. This is an expensive calculation for large datasets.
This PR reverts back to the original behavior.

Only get bounds on paginated queryset on home page

---

django-rgd-imagery/rgd_imagery/urls.py

Closes https://github.com/ResonantGeoData/ResonantGeoData/issues/644
URLs are routed greedily. For example, in the following:
```python
router = SimpleRouter(trailing_slash=False)
router.register(r'api/a', SerializerA)
router.register(r'api/a/b', SerializerAB)
```
... a `POST` to `/api/a/b` would actually use `SerializerA` since the route is a full match.
This PR corrects the orders of URLs in the `rgd_image` application to prevent this issue.

Reorder `rgd_image` URLs

---

django-rgd/client/rgd_client/plugin.py
django-rgd/tests/test_client.py

Addresses part of #629
Note: The test for this client method is intentionally brief, as the endpoint itself already has its own tests, and rewriting those for the client would be redundant.
This PR made me consider the following: Should we be modeling the data in python with Dataclasses / Pydantic / etc.? Would it provide value? Or should we just keep things as dicts. I wouldn't address this here, but just a thought. cc @banesullivan

Add `file_tree_search` client method

---

django-rgd-imagery/README.md
django-rgd-imagery/rgd_imagery/stac/tests.py
django-rgd-imagery/rgd_imagery/stac/views.py
django-rgd/rgd/configuration/configuration.py

Closes https://github.com/ResonantGeoData/ResonantGeoData/issues/654
We previously had to impose this hard limit to deal with STAC Browser and the lack of pagination it allowed. Now, the STAC API supports pagination in the STAC ItemCollection view. This PR brings in that already implemented feature.

Remove RGD_STAC_BROWSER_LIMIT

---

django-rgd-3d/setup.py
django-rgd-fmv/setup.py
django-rgd-geometry/setup.py
django-rgd-imagery/setup.py

RGD is not stable enough to guarantee cross-version compatibility between the core package and subpackages. For this reason, they currently share the same versions.
To further safeguard this, `django-rgd` should be pinned in the subpackages to guarantee a working installation.
Also, I think/hope this will improve using dependabot as it should pick up on the coupled dependencies so that all of these packages get bumped in a single PR instead of an individual PR for each subpackage

Pin django-rgd dep in subpackages

---

docker-compose.override.yml

Pin `flower` services to `mher/flower:0.9.5` due to several issues:
1. Recent releases of flower are not compatible with celery broker URL
2. DockerHub image for `mher/flower` is not following best practices

Fix flower service in docker-compose

---

.github/workflows/build_dev_wheels.yml
version.py

Sets up a new GitHub action to publish wheels/sdist from `main` to GitHub Pages. Why? So that we can easily install from `main` for testing downstream projects without publishing a release to PyPI. Installing from git source isn't all that easy for us in some environments but using `--find-links` is.
Check out https://resonantgeodata.github.io/ResonantGeoData/
This also builds the wheels for every PR and uploads as a build artifact

Publish dev wheels from `main`

---

.github/workflows/docker-package.yml
dev/miniforge.Dockerfile
django-rgd-imagery/setup.py
django-rgd/setup.py
docker-compose.override.miniforge.yml
docker-compose.override.no-build.yml
environment.yml
example_project/README.md
example_project/setup.py

Hopefully, this makes it easier to run RGD within docker (or natively) on an M1 Mac - cc @mcovalt 
At the moment, this will not work with the tox testing environment.
To test:
```bash
docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.override.miniforge.yml build
docker compose -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.override.miniforge.yml up
```
Current image sizes:
```
REPOSITORY                          TAG          IMAGE ID       CREATED        SIZE
django                              latest       4fc25bb20b1b   11 seconds ago   1.37GB
celery                              latest       3f82a97a1242   2 minutes ago    2.93GB
miniforge                           latest       0dc419cbbdaf   2 days ago       4.94GB
```
Once we …

Miniforge docker image and publish images to ghcr.io

---

django-rgd-imagery/rgd_imagery/admin/base.py
django-rgd-imagery/rgd_imagery/models/base.py

I was using the Django admin to debug #666 and I noticed the `Image` and `ImageSet` list pages were taking 3-5 seconds to load. It turns out, for N rows in the image/image set tables, approximately O(2N) SQL queries are being executed on page load. So, I made some optimizations to make debugging less painful. 
With these changes, my `ImageSet` list page went from 204 queries to 5 queries for 71 rows. It looks like there's still some repetitive queries being made, but not enough to have a major impact on page load time.

Optimize rgd_imagery admin page queries

---

django-rgd/rgd/filters.py
django-rgd/rgd/templates/rgd/_include/search_fields.html

@banesullivan the issue specifies "A user wants to be able to search for SpatialEntries that have x% overlap with the search geometry". I implemented this so all SpatialEntries that overlap the search geometry by *at least* x% are shown. I figured that is better than only matching the exact percentage given. Does that make sense, or do we want an exact match?
Closes #462

Add `percent_overlap` filter

---

django-rgd-imagery/tests/test_client.py
django-rgd/README.md
django-rgd/tests/test_client.py
testing-utils/rgd_testing_utils/settings.py

Closes #638 
The problem was that the test app didn't have pagination enabled, so it was just returning a flat list instead of a dict of the form
```
{
"count": 100,
"next": "http://localhost:8000/api/rgd/checksum_file?limit=100&offset=100",
"previous": null,
"results": [....]
}
```

Set `DEFAULT_PAGINATION_CLASS` and `PAGE_SIZE` in test app

---

django-rgd/tests/test_client.py

Closes #643 
This PR adds tests for all of the python client methods that were missing one. As for the failing methods mentioned in the issue, it seems they have been fixed because all tests are passing and we now have test coverage for every client method.

Add tests for all python client methods that didn't have one

---

django-rgd-3d/rgd_3d/tasks/etl.py
django-rgd-3d/tests/test_point_cloud.py
django-rgd-imagery/rgd_imagery/tasks/subsample.py
django-rgd/client/rgd_client/pytorch.py
django-rgd/rgd/management/commands/_data_helper.py
django-rgd/rgd/models/file.py
django-rgd/rgd/models/utils.py
django-rgd/rgd/rest/viewsets.py
django-rgd/rgd/utility.py
django-rgd/tests/test_checksumfile.py

This adds a new feature to be able to control how some of RGD's ETL routines save generated/converted data as we may not always want to upload the data to S3FF.
On a downstream project, I need to save the data to a local path on disk rather than in minio/S3FF and this feature enables that.

Add RGD_OUTPUT_FILE_HANDLER

---

django-rgd-3d/rgd_3d/templates/rgd_3d/_include/vtkjs_viewer.html

The main source of this bug was that it was using a `z-index` to overlay the "Loading" text on top of the VTK viewer. The overlaid elements had a `position` of  `relative`, which doesn't work with `z-index`. I fixed it by changing them to have `position: absolute`; this introduced some alignment issues which I fixed with flexbox.
Here's what it looks like now - (I throttled my download speed so that the loading bar shows up for an extended period of time)

Fix VTK viewer styling on Mesh3D admin page

---

django-rgd-fmv/rgd_fmv/serializers.py

Currently, since it is a `BinaryField`, the `FMVMeta.frame_numbers` field is not deserialized before being sent as part of the response. So, the value returned as part of the fmv `/data` endpoint response isn't readable by the client, as it comes back as what appears to be a string encoding of the data. This PR updates the serializer to explicitly serialize the data into a JSON array before sending it back to the client.

Deserialize `frame_numbers` to array in FMV data endpoint

---

django-rgd-fmv/rgd_fmv/serializers.py

Updates the serializer to return a GeoJSON footprint instead of a string

Patch `FMVMetaDataSerializer` to return footprints as GeoJSON instead of SRID string

---

django-rgd-fmv/rgd_fmv/tasks/etl.py
django-rgd-fmv/setup.py
version.py

I've encountered some FMVs that don't have corner points as part of their spatial reference, but do have Geodetic Frame Center and Target Width fields through which this info can be derived (or maybe it's just an approximation, i'm not actually sure) . This PR adds support for these fields to the fmv ETL routine as a fallback if corner points aren't available.

Support additional KLV metadata fields in FMV ETL routine
